version: '3.0'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: pokemonshop
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"