// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokemonShop.Data;

namespace PokemonShop.Migrations
{
    [DbContext(typeof(PokemonShopDbContext))]
    [Migration("20210502115404_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("PokemonShop.Data.Entities.Order", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("GUID");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("NAME");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("START_DATE");

                    b.Property<string>("Telephone")
                        .HasColumnType("longtext")
                        .HasColumnName("TELEPHONE");

                    b.HasKey("Guid");

                    b.ToTable("ORDERS");
                });
#pragma warning restore 612, 618
        }
    }
}
